export const DATE_FORMAT = 'YYYY-MM-DD';

export const COLLECTION_TYPES = ['ONSITE', 'VIRTUAL', '3D_SCAN'] as const;
export type TCollectionType = (typeof COLLECTION_TYPES)[number];

export const CONTACT_METHODS = ['PHONE', 'EMAIL'] as const;
export type TContactMethod = (typeof CONTACT_METHODS)[number];

export const PROPERTY_TYPES = ['SF', 'CONDO'] as const;
export type TPropertyType = (typeof PROPERTY_TYPES)[number];

export const LOT_SIZE_UNITS = ['SQUARE_FEET'] as const;
export type TLotSizeUnits = (typeof PROPERTY_TYPES)[number];

export const PROPERTY_DATA_COLLECTOR_TYPES = [
  'APPRAISER',
  'APPRAISER_TRAINEE',
  'INSURANCE_INSPECTOR',
  'REAL_ESTATE_AGENT',
  'NOTARY_PUBLIC',
  'SMART_HOME_SERVICES',
  'PHOTOGRAPHER',
  'PROPERTY_PRESERVATION_AGENT',
  'HOME_INSPECTOR',
  'HOMEOWNER',
  'OTHER',
] as const;
export type TPropertyDataCollectorType = (typeof PROPERTY_DATA_COLLECTOR_TYPES)[number];

export const LOCATION_DESCRIPTION_TYPES = [
  'BORDERING_AMENITIES',
  'BORDERING_RAIL_STOP',
  'BORDERING_TROLLEY_STOP',
  'BORDERING_CITY_BUS_STOP',
  'BORDERING_BEACH',
  'BORDERING_RECREATION',
  'GATED_COMMUNITY',
  'OCEAN_FRONT_BEACH',
  'OCEAN_FRONT_NO_BEACH',
  'INLAND_SALTWATER_FRONT_BEACH',
  'INLAND_SALTWATER_FRONT_NO_BEACH',
  'LAKE_FRONT_BEACH',
  'LAKE_FRONT_NO_BEACH',
  'SEASONAL_LAKE_FRONT',
  'RIVER_CANAL_FRONT',
  'BORDERING_GOLF_COURSE',
  'GOLF_COURSE_COMMUNITY',
  'RESIDENTIAL',
  'BORDERING_INDUSTRIAL_USE',
  'BORDERING_COMMERCIAL_USE',
  'BORDERING_SCHOOL',
  'BORDERING_VACANT_LAND',
  'BORDERING_HOSPITAL',
  'BORDERING_RESTAURANT',
  'BORDERING_HOTEL_MOTEL_INN',
  'ON_CUL_DE_SAC_STREET',
  'ON_OR_BORDERING_BUSY_ROAD',
  'ON_OR_BORDERING_INTERSTATE_HWY',
  'AIR_TRAFFIC_DIRECTLY_OVERHEAD',
  'BORDERING_PARK',
  'BORDERING_OVERHEAD_ELECTRIC_POWER_TRANSMISSION_LINE',
  'BORDERING_LANDFILL',
  'NOTABLE_NOISE',
  'NOTABLE_ODOR',
  'OTHER_ADVERSE',
  'OTHER_BENEFICIAL',
  'OTHER_NEUTRAL',
] as const;
export type TLocationDescriptionType = (typeof LOCATION_DESCRIPTION_TYPES)[number];

export const VIEW_DESCRIPTION_TYPES = [
  'NONE_NOTABLE',
  'VACANT_LOT',
  'WOODS_TREED_PRIVATE',
  'HILLS_FOOTHILLS',
  'GREENBELT_OPEN_SPACE',
  'MOUNTAIN',
  'MOUNTAIN_RANGE',
  'POND',
  'LAKE',
  'CANAL',
  'OCEAN',
  'RIVER',
  'CREEK',
  'BAY',
  'SOUND',
  'LAGOON',
  'MARINA',
  'INTRACOASTAL_WATERWAY',
  'HARBOR',
  'GULF',
  'WETLANDS',
  'BAYOU',
  'MARSH',
  'COMMERCIAL',
  'PARKING_LOT',
  'INDUSTRIAL',
  'MILITARY_BASE',
  'RAILROAD',
  'INTERSTATE',
  'ELEVATED_OVERPASS',
  'PASTURES_FIELDS_ETC',
  'AGRICULTURAL_FARM_ETC',
  'DESERT',
  'CANYON',
  'VALLEY',
  'COUNTRYSIDE',
  'RAVINE',
  'CITY_SKYLINE',
  'GOLF_COURSE',
  'PARK',
  'APARTMENT_COMPLEX',
  'WINDMILL_WINDFARM',
  'OVERHEAD_ELECTRIC_POWER_TRANSMISSION_LINE',
  'SCHOOL',
] as const;
export type TViewDescriptionType = (typeof VIEW_DESCRIPTION_TYPES)[number];

// viewQuality
export const VIEW_QUALITIES = ['FULL', 'PARTIAL'] as const;
export type TViewQuality = (typeof VIEW_QUALITIES)[number];

export const ADVERSE_TYPES = [
  'CONTAMINATION',
  'FAILING_SITE_IMPROVEMENT',
  'ENCROACHMENTS',
  'SIGNIFICANT_JUNK_TRASH',
  'SINKHOLE',
  'WETLANDS',
  'EXTREME_SLOPE',
  'OTHER',
  'NONE_OBSERVED',
] as const;
export type TAdverseType = (typeof ADVERSE_TYPES)[number];

export const PROPERTY_IMPROVEMENT_TYPES = [
  'ORNATE_LANDSCAPING',
  'IRRIGATION_SYSTEM',
  'GRAYWATER_SYSTEM',
  'WATER_COLLECTION_SYSTEM',
  'OUTDOOR_KITCHEN',
  'INGROUND_POOL',
  'INGROUND_HOTTUB',
  'SPORTS_COURT',
  'SAUNA',
  'ORCHARD_HOBBY',
  'VINEYARD_HOBBY',
  'FENCE',
  'GAZEBO',
  'GREENHOUSE',
  'TOOL_SHED',
  'PATIO',
  'DECK',
  'BALCONY',
  'UNCOVERED_PORCH',
  'COVERED_PORCH',
  'ENCLOSED_PORCH',
  'WRAP_AROUND_PORCH',
  'STOOP',
  'FIREPIT',
  'OUTDOOR_FIREPLACE',
  'OTHER',
  'NONE',
  'CARPORT',
  'ABOVE_GROUND_POOL',
] as const;
export type TPropertyImprovementType = (typeof PROPERTY_IMPROVEMENT_TYPES)[number];

export const POOL_CONCERN_TYPES = [
  'NONE',
  'EMPTY_AND_UNCOVERED',
  'DAMAGED',
  'MISSING_EQUIPMENT',
  'DAMAGED_POOL_ENCLOSURE',
  'UNSANITARY_WATER',
] as const;
export type TPoolConcernType = (typeof POOL_CONCERN_TYPES)[number];

// nonResidentialUseType
export const NON_RESIDENTIAL_USE_TYPES = [
  'CHILDCARE',
  'ELDERCARE',
  'BOARDING_HOUSE',
  'AUTO_SHOP',
  'MEDICAL',
  'SALON',
  'OFFICE',
  'RETAIL',
  'HOTEL_BED_BREAKFAST',
  'FOOD_SERVICE',
  'AGRICULTURE',
  'GROW_ROOM',
  'OTHER',
  'NONE_OBSERVED',
] as const;
export type TNonResidentialUseType = (typeof NON_RESIDENTIAL_USE_TYPES)[number];

// waterfrontImprovementType
export const WATERFRONT_IMPROVEMENT_TYPES = [
  'SEAWALL',
  'FLOATING_DOCK',
  'BOAT_LIFT',
  'DOCK',
  'PIER',
  'BOAT_HOUSE',
  'BOAT_RAMP',
  'NONE',
] as const;
export type TWaterfrontImprovementType = (typeof WATERFRONT_IMPROVEMENT_TYPES)[number];

// roadOwnershipType
export const ROAD_OWNERSHIP_TYPES = ['PUBLIC', 'PRIVATE', 'UNKNOWN'] as const;
export type TRoadOwnershipType = (typeof ROAD_OWNERSHIP_TYPES)[number];

// electricalType
export const ELECTRICAL_TYPES = [
  'PUBLIC',
  'SOLAR',
  'GENERATOR',
  'WIND',
  'HYDRO_ELECTRIC',
  'NO_ELECTRICAL_SERVICE',
] as const;
export type TElectricalType = (typeof ELECTRICAL_TYPES)[number];

// sewerType
export const SEWER_TYPES = ['PUBLIC', 'SEPTIC', 'CESSPOOL', 'NONE'] as const;
export type TSewerType = (typeof SEWER_TYPES)[number];

// waterType
export const WATER_TYPES = ['PUBLIC', 'WELL', 'CISTERN', 'HAULED_WATER'] as const;
export type TWaterType = (typeof WATER_TYPES)[number];

// gasType
export const GAS_TYPES = ['PUBLIC', 'PRIVATE', 'NONE'] as const;
export type TGasType = (typeof GAS_TYPES)[number];

export const BUILDINGS_STRUCTURE_TYPES = [
  'DWELLING',
  'WORKSHOP',
  'BARN',
  'POLE_BUILDING',
  'STABLES',
  'RIDING_ARENA',
  'POOL_HOUSE',
  'DETACHED_GARAGE',
  'OTHER_OUTBUILDING',
] as const;

export const BUILDINGS_ATTACHMENT_TYPES = [
  'ATTACHED',
  'DETACHED',
  'LEFT_SEMI_DETACHED',
  'RIGHT_SEMI_DETACHED',
] as const;

// BUILDINGS_FOUNDATION_TYPES
export const BUILDINGS_FOUNDATION_TYPES = [
  'SLAB',
  'CRAWLSPACE',
  'BASEMENT',
  'POST_PIER',
  'RUNNER',
] as const;

export const BUILDINGS_CONSTRUCTION_STATUS = [
  'COMPLETE',
  'INCOMPLETE_CONSTRUCTION',
  'INCOMPLETE_RENOVATION_CONSTRUCTION',
  'PROPOSED',
] as const;

export const BUILDINGS_CONSTRUCTION_TYPES = [
  'FRAME',
  'MASONRY',
  'LOG',
  'MANUFACTURED',
  'MODULAR',
  'GEODESIC',
  'EARTH_BERM',
  '3D_PRINTED',
] as const;

export const BUILDINGS_DESIGN = [
  'GARDEN',
  'LOW_RISE',
  'MID_RISE',
  'HIGH_RISE',
  'ROWHOUSE_TOWNHOUSE',
  'DETACHED',
  'OTHER',
] as const;

export const EXTERIOR_DEFICIENCY_NAMES = [
  'FOUNDATION',
  'ROOF',
  'SIDING',
  'FASCIA',
  'WINDOWS',
  'DOORS',
  'GUTTERS_DOWNSPOUTS',
  'EAVES',
  'CHIMNEY',
  'PORCH',
  'PATIO',
  'DECK',
  'BALCONY',
  'ENTRY_STAIRS',
  'CARPORT',
  'DRIVEWAY',
  'INCOMPLETE_LANDSCAPING',
  'OTHER',
  'EXTERIOR_WALLS',
  'NONE_OBSERVED',
] as const;

export const EXTERIOR_DEFICIENCY_TYPES = [
  'EXCESSIVE_WEAR',
  'DAMAGE',
  'EVIDENCE_OF_INFESTATION',
  'MISSING',
  'OTHER',
] as const;

export const EXTERIOR_DEFICIENCY_DETAIL_FUNDATION = [
  'ERODED_MATERIAL',
  'CRACKING',
  'SETTLEMENT',
  'EVIDENCE_OF_MOISTURE',
  'SEEPAGE',
  'INFESTATION',
  'LEANING_OR_BOWING_WALLS',
  'HEAVING',
  'OTHER',
] as const;

export const EXTERIOR_DEFICIENCY_DETAIL_EXTERIOR_WALLS = [
  'ERODED_MATERIAL',
  'CRACKING',
  'HOLES',
  'DRY_ROT',
  'MOISTURE_ROT',
  'SETTLEMENT',
  'WIND_DAMAGE',
  'MISSING_MATERIAL',
  'OTHER',
] as const;

export const EXTERIOR_DEFICIENCY_DETAIL_ROOF_SURFACE = [
  'ERODED_MATERIAL',
  'CRACKING',
  'TARP_ON_ROOF',
  'LEAK_EVIDENT',
  'MISSING_MATERIAL',
  'WOOD_ROT',
  'SOFFIT_DAMAGE',
  'FASCIA_DAMAGE',
  'OTHER',
] as const;

export const EXTERIOR_DEFICIENCY_DETAIL_GUTTERS_AND_DOWNSPUTS = [
  'ERODED_MATERIAL',
  'CRACKING',
  'MISSING_DOWNSPOUTS',
  'DAMAGED',
  'LEAKING',
  'INFESTATION',
  'IMPROPER_FLOW',
  'MISSING_GUTTER',
  'OTHER',
] as const;

export const EXTERIOR_DEFICIENCY_DETAIL_WINDOWS = [
  'CRACKING',
  'MISSING_WINDOW_PANE',
  'DRY_ROT',
  'BROKEN_GLASS',
  'BOARDED_UP',
  'MISSING_WINDOW',
  'EXPOSED_WOOD',
  'STORM_SASH_DAMAGE',
  'THERMOPANE_DAMAGE',
  'OTHER',
] as const;

// exteriorUpdatedComponent
// NONE_OBSERVED, SIDING, DOORS, WALLS, ROOF, FOUNDATION, FENCE, OTHER, WINDOWS
export const EXTERIOR_UPDATED_COMPONENT = [
  'NONE_OBSERVED',
  'SIDING',
  'DOORS',
  'WALLS',
  'ROOF',
  'FOUNDATION',
  'FENCE',
  'OTHER',
  'WINDOWS',
] as const;

// exteriorUpdateType
// FULLY_UPDATED, PARTIALLY_UPDATED
export const EXTERIOR_UPDATE_TYPE = ['FULLY_UPDATED', 'PARTIALLY_UPDATED'] as const;

// exteriorUpdateTimeframe
// LESS_THAN_1_YEAR, 1_TO_10_YEARS, 10_TO_20_YEARS, MORE_THAN_20_YEARS
export const EXTERIOR_UPDATE_TIMEFRAME = [
  'LESS_THAN_1_YEAR',
  '1_TO_10_YEARS',
  '10_TO_20_YEARS',
  'MORE_THAN_20_YEARS',
] as const;

// heatingType
// CENTRAL_HOT_AIR, HOT_WATER_RADIATORS, HOT_WATER_BASEBOARD, ELECTRIC_BASEBOARD, IN_WALL_HEATER, RADIANT_FLOOR, CENTRAL_HEATPUMP, DUCTLESS_HEATPUMP, DUCTLESS_HEAT, GEOTHERMAL, WALL_FURNACE, GAS_FURNACE, OIL_FURNACE, COAL_FURNACE, NO_HEAT
export const HEATING_TYPE = [
  'CENTRAL_HOT_AIR',
  'HOT_WATER_RADIATORS',
  'HOT_WATER_BASEBOARD',
  'ELECTRIC_BASEBOARD',
  'IN_WALL_HEATER',
  'RADIANT_FLOOR',
  'CENTRAL_HEATPUMP',
  'DUCTLESS_HEATPUMP',
  'DUCTLESS_HEAT',
  'GEOTHERMAL',
  'WALL_FURNACE',
  'GAS_FURNACE',
  'OIL_FURNACE',
  'COAL_FURNACE',
  'NO_HEAT',
] as const;

// coolingType
// CENTRAL_AIR_CONDITIONING, CENTRAL_HEATPUMP, DUCTLESS_HEATPUMP, DUCTLESS_AIR_CONDITIONING, WHOLE_HOUSE_FAN, EVAPORATIVE_COOLER, GEOTHERMAL, NONE
export const COOLING_TYPE = [
  'CENTRAL_AIR_CONDITIONING',
  'CENTRAL_HEATPUMP',
  'DUCTLESS_HEATPUMP',
  'DUCTLESS_AIR_CONDITIONING',
  'WHOLE_HOUSE_FAN',
  'EVAPORATIVE_COOLER',
  'GEOTHERMAL',
  'NONE',
] as const;

// mechanicalDeficiencyName
// NONE_OBSERVED, PLUMBING, ELECTRICAL, HEATING, WATER_HEATER, COOLING, SUMP_PUMP, OTHER
export const MECHANICAL_DEFICIENCY_NAME = [
  'NONE_OBSERVED',
  'PLUMBING',
  'ELECTRICAL',
  'HEATING',
  'WATER_HEATER',
  'COOLING',
  'SUMP_PUMP',
  'OTHER',
] as const;

// mechanicalDeficiencyType
// EXCESSIVE_WEAR, DAMAGE, MISSING, NON_FUNCTIONAL, EVIDENCE_OF_LEAKS, EVIDENCE_OF_FIRE, OTHER
export const MECHANICAL_DEFICIENCY_TYPE = [
  'EXCESSIVE_WEAR',
  'DAMAGE',
  'MISSING',
  'NON_FUNCTIONAL',
  'EVIDENCE_OF_LEAKS',
  'EVIDENCE_OF_FIRE',
  'OTHER',
] as const;

// mechanicalUpdatedComponent
// PLUMBING, ELECTRICAL, HEATING, WATER_HEATER, COOLING, SUMP_PUMP, OTHER, NONE_OBSERVED
export const MECHANICAL_UPDATE_COMPONENT = [
  'PLUMBING',
  'ELECTRICAL',
  'HEATING',
  'WATER_HEATER',
  'COOLING',
  'SUMP_PUMP',
  'OTHER',
  'NONE_OBSERVED',
] as const;

// mechanicalUpdateType
// FULLY_UPDATED, PARTIALLY_UPDATED
export const MECHANICAL_UPDATE_TYPE = ['FULLY_UPDATED', 'PARTIALLY_UPDATED'] as const;

// mechanicalUpateTimeframe
// LESS_THAN_1_YEAR, 1_TO_5_YEARS, 5_TO_10_YEARS, 10_OR_MORE_YEARS
export const MECHANICAL_UPDATE_TIMEFRAME = [
  'LESS_THAN_1_YEAR',
  '1_TO_5_YEARS',
  '5_TO_10_YEARS',
  '10_OR_MORE_YEARS',
] as const;

// garageType
// ATTACHED_GARAGE, DETACHED_GARAGE, BUILTIN_GARAGE, NONE
export const GARAGE_TYPE = [
  'ATTACHED_GARAGE',
  'DETACHED_GARAGE',
  'BUILTIN_GARAGE',
  'NONE',
] as const;

// garageDeficiencyName
// NONE_OBSERVED, SIDING, WINDOWS, DOORS, GARAGE_DOOR, EXTERIOR_WALLS, INTERIOR_WALLS, CEILING, ROOF, FOUNDATION, OTHER
export const GARAGE_DEFICIENCY_NAME = [
  'NONE_OBSERVED',
  'SIDING',
  'WINDOWS',
  'DOORS',
  'GARAGE_DOOR',
  'EXTERIOR_WALLS',
  'INTERIOR_WALLS',
  'CEILING',
  'ROOF',
  'FOUNDATION',
  'OTHER',
] as const;

// garageDeficiencyType
//EXCESSIVE_WEAR, EVIDENCE_OF_INFESTATION, MISSING, OTHER
export const GARAGE_DEFICIENCY_TYPE = [
  'EXCESSIVE_WEAR',
  'EVIDENCE_OF_INFESTATION',
  'MISSING',
  'OTHER',
] as const;

// garageDeficiencyDetailFoundation
// ERODED_MATERIAL, CRACKING, SETTLEMENT, EVIDENCE_OF_MOISTURE, SEEPAGE, INFESTATION, LEANING_OR_BOWED_WALLS, HEAVING, OTHER
export const GARAGE_DEFICIENCY_DETAIL_FOUNDATION = [
  'ERODED_MATERIAL',
  'CRACKING',
  'SETTLEMENT',
  'EVIDENCE_OF_MOISTURE',
  'SEEPAGE',
  'INFESTATION',
  'LEANING_OR_BOWED_WALLS',
  'HEAVING',
  'OTHER',
] as const;

// garageDeficiencyDetailExteriorWalls
// ERODED_MATERIAL, CRACKING, HOLES, DRY_ROT, MOISTURE_ROT, SETTLEMENT, WIND_DAMAGE, MISSING_MATERIAL, OTHER
export const GARAGE_DEFICIENCY_DETAIL_EXTERIOR_WALLS = [
  'ERODED_MATERIAL',
  'CRACKING',
  'HOLES',
  'DRY_ROT',
  'MOISTURE_ROT',
  'SETTLEMENT',
  'WIND_DAMAGE',
  'MISSING_MATERIAL',
  'OTHER',
] as const;

// garageDeficiencyDetailRoofSurface
// ERODED_MATERIAL, CRACKING, TARP_ON_ROOF, LEAK_EVIDENT, MISSING_MATERIAL, WOOD_ROT, SOFFIT_DAMAGE, FASCIA_DAMAGE, OTHER
export const GARAGE_DEFICIENCY_DETAIL_ROOF_SURFACE = [
  'ERODED_MATERIAL',
  'CRACKING',
  'TARP_ON_ROOF',
  'LEAK_EVIDENT',
  'MISSING_MATERIAL',
  'WOOD_ROT',
  'SOFFIT_DAMAGE',
  'FASCIA_DAMAGE',
  'OTHER',
] as const;

// garageDeficiencyDetailWindows
// CRACKING, MISSING_WINDOW_PANE, EXPOSED_WOOD, STORM_SASH_DAMAGE, THERMOPANE_DAMAGE, OTHER
export const GARAGE_DEFICIENCY_DETAIL_WINDOWS = [
  'CRACKING',
  'MISSING_WINDOW_PANE',
  'EXPOSED_WOOD',
  'STORM_SASH_DAMAGE',
  'THERMOPANE_DAMAGE',
  'OTHER',
] as const;

// garageDeficiencyDetailCeiling
// DISCOLORATION, MISSING, CRUMBLING, WATER_DAMAGE, OTHER
export const GARAGE_DEFICIENCY_DETAIL_CEILING = [
  'DISCOLORATION',
  'MISSING',
  'CRUMBLING',
  'WATER_DAMAGE',
  'OTHER',
] as const;

// garageDeficiencyDetailInteriorWalls
// DISCOLORATION, MISSING, CRUMBLING, WATER_DAMAGE, OTHER
export const GARAGE_DEFICIENCY_DETAIL_INTERIOR_WALLS = [
  'DISCOLORATION',
  'MISSING',
  'CRUMBLING',
  'WATER_DAMAGE',
  'OTHER',
] as const;

// belowGradeExits
// WALKUP, WALKOUT, GARAGE, CELLAR_DOOR, INTERIOR
export const BELOW_GRADE_EXITS = [
  'WALKUP',
  'WALKOUT',
  'GARAGE',
  'CELLAR_DOOR',
  'INTERIOR',
] as const;

// atticAccess
// ATTIC_SCUTTLE, DROP_STAIR, PERMANENT_STAIRWELL, DOOR, NONE_OBSERVED
export const ATTIC_ACCESS = [
  'ATTIC_SCUTTLE',
  'DROP_STAIR',
  'PERMANENT_STAIRWELL',
  'DOOR',
  'NONE_OBSERVED',
] as const;

// roomType
// FOYER, LIVING_ROOM, DINING_ROOM, KITCHEN, DEN, FAMILY_ROOM, REC_ROOM, BEDROOM,  FULL_BATH, HALF_BATH, LAUNDRY_ROOM, HALL, LIBRARY, MEDIA, OFFICE, UTILITY_ROOM, WORKSHOP, BUTLERS_PANTRY, OTHER_ROOM, UNFINISHED_BASEMENT
export const ROOM_TYPE = [
  'FOYER',
  'LIVING_ROOM',
  'DINING_ROOM',
  'KITCHEN',
  'DEN',
  'FAMILY_ROOM',
  'REC_ROOM',
  'BEDROOM',
  'FULL_BATH',
  'HALF_BATH',
  'LAUNDRY_ROOM',
  'HALL',
  'LIBRARY',
  'MEDIA',
  'OFFICE',
  'UTILITY_ROOM',
  'WORKSHOP',
  'BUTLERS_PANTRY',
  'OTHER_ROOM',
  'UNFINISHED_BASEMENT',
] as const;

// fixtureType
// SINK, TOILET, TUB_SHOWER, WALK_IN_SHOWER, TUB_W_NO_SHOWER, FREESTANDING_TUB, APPLIANCE_HOOKUP, LAUNDRY_HOOKUP, POT_FILLER, JETTED_TUB, ROUGH_IN, NONE_OBSERVED
export const FIXTURE_TYPE = [
  'SINK',
  'TOILET',
  'TUB_SHOWER',
  'WALK_IN_SHOWER',
  'TUB_W_NO_SHOWER',
  'FREESTANDING_TUB',
  'APPLIANCE_HOOKUP',
  'LAUNDRY_HOOKUP',
  'POT_FILLER',
  'JETTED_TUB',
  'ROUGH_IN',
  'NONE_OBSERVED',
] as const;

// roomFeatureType
// FIREPLACE, WOOD_STOVE, BUILT_INS, WET_BAR, WALK_IN_CLOSET, PANTRY, NONE
export const ROOM_FEATURE_TYPE = [
  'FIREPLACE',
  'WOOD_STOVE',
  'BUILT_INS',
  'WET_BAR',
  'WALK_IN_CLOSET',
  'PANTRY',
  'NONE',
] as const;

// interiorDeficiencyName
// FLOORING, PLUMBING_FIXTURES, ELECTRICAL_FIXTURES, CABINET_COUNTERTOPS, APPLIANCES, WALLS, CEILING, SHOWER_TUB_SURROUND, OTHER, NONE_OBSERVED
export const INTERIOR_DEFICIENCY_NAME = [
  'FLOORING',
  'PLUMBING_FIXTURES',
  'ELECTRICAL_FIXTURES',
  'CABINET_COUNTERTOPS',
  'APPLIANCES',
  'WALLS',
  'CEILING',
  'SHOWER_TUB_SURROUND',
  'OTHER',
  'NONE_OBSERVED',
] as const;

// interiorDeficiencyType
// EXCESSIVE_WEAR, DAMAGE, EVIDENCE_OF_MOLD, EVIDENCE_OF_INFESTATION, MISSING, POOR_FUNCTIONAL_UTILITY, OTHER
export const INTERIOR_DEFICIENCY_TYPE = [
  'EXCESSIVE_WEAR',
  'DAMAGE',
  'EVIDENCE_OF_MOLD',
  'EVIDENCE_OF_INFESTATION',
  'MISSING',
  'POOR_FUNCTIONAL_UTILITY',
  'OTHER',
] as const;

// interiorDeficiencyDetailFlooring
// BUCKLED, HOLES, SAGGING, SPONGY, INFESTATION, DRY_ROT, DISCOLORATION, CRACKS, UNFINISHED_SECTION, DAMPNESS, OTHER
export const INTERIOR_DEFICIENCY_DETAIL_FLOORING = [
  'BUCKLED',
  'HOLES',
  'SAGGING',
  'SPONGY',
  'INFESTATION',
  'DRY_ROT',
  'DISCOLORATION',
  'CRACKS',
  'UNFINISHED_SECTION',
  'DAMPNESS',
  'OTHER',
] as const;

// interiorDeficiencyDetailCeiling
// DISCOLORATION, MISSING, CRUMBLING, WATER_DAMAGE, OTHER
export const INTERIOR_DEFICIENCY_DETAIL_CEILING = [
  'DISCOLORATION',
  'MISSING',
  'CRUMBLING',
  'WATER_DAMAGE',
  'OTHER',
] as const;

// interiorDeficiencyDetailWalls
// DISCOLORATION, MISSING, CRUMBLING, WATER_DAMAGE, OTHER
export const INTERIOR_DEFICIENCY_DETAIL_WALLS = [
  'DISCOLORATION',
  'MISSING',
  'CRUMBLING',
  'WATER_DAMAGE',
  'OTHER',
] as const;

// interiorUpdatedComponent
// FLOORING, PLUMBING_FIXTURES, ELECTRICAL_FIXTURES, CABINET_COUNTERTOPS, APPLIANCES, WALLS, CEILING, OTHER, NONE_OBSERVED
export const INTERIOR_UPDATED_COMPONENT = [
  'FLOORING',
  'PLUMBING_FIXTURES',
  'ELECTRICAL_FIXTURES',
  'CABINET_COUNTERTOPS',
  'APPLIANCES',
  'WALLS',
  'CEILING',
  'OTHER',
  'NONE_OBSERVED',
] as const;

// interiorUpdateType
// FULLY_UPDATED, PARTIALLY_UPDATED
export const INTERIOR_UPDATE_TYPE = ['FULLY_UPDATED', 'PARTIALLY_UPDATED'] as const;

// interiorUpdateTimeframe
// LESS_THAN_1_YEAR, 1_TO_5_YEARS, 5_TO_10_YEARS, 10_OR_MORE_YEARS
export const INTERIOR_UPDATE_TIMEFRAME = [
  'LESS_THAN_1_YEAR',
  '1_TO_5_YEARS',
  '5_TO_10_YEARS',
  '10_OR_MORE_YEARS',
] as const;
